apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopmate

resources:
  - namespace.yml
  - backend-deployment.yml
  - frontend-deployment.yml
  - agent-deployment.yml
  - ingress.yml
  - redis-deployment.yml
  - postgres-deployment.yml
  - configmap.yml
  - reliability.yml
