#!/bin/sh
set -eu

escaped_password=$(printf "%s" "$POSTGRES_APP_PASSWORD" | sed "s/'/''/g")
role_exists=$(psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Atc "SELECT 1 FROM pg_roles WHERE rolname = '$POSTGRES_APP_USER'")
if [ "$role_exists" = "1" ]; then
  psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "ALTER ROLE \"$POSTGRES_APP_USER\" LOGIN PASSWORD '$escaped_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;"
else
  psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE ROLE \"$POSTGRES_APP_USER\" LOGIN PASSWORD '$escaped_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;"
fi

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<SQL
GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_APP_USER";
GRANT USAGE ON SCHEMA public TO "$POSTGRES_APP_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$POSTGRES_APP_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "$POSTGRES_APP_USER";
SQL
